### ISSUE TITLE
Installation fails if R version is not up to date

### ISSUE THREAD

**Issue by hplieninger** [profandyfield/adventr#11]
First of all, thanks for all the great resources.

Installation from GitHub fails for me, because my R version is 3.6.2, see below. While I can work around this using `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")`, newbies might have more trouble.

Would it be possible to move tidyverse (and learnr) from `Depends` to `Imports`? Maybe one could call `library("tidyverse")` inside `.onLoad()`, if this is desired. Or, maybe, globally `@import tidyverse` will suffice?

``` r
remotes::install_github("profandyfield/adventr")
#> Installing package into 'C:/Users/hp/Documents/R/win-library/3.6'
#> (as 'lib' is unspecified)
#> * installing *source* package 'adventr' ...
#> ** using staged installation
#> ** R
#> ** data
#> *** moving datasets to lazyload DB
#> ** inst
#> ** byte-compile and prepare package for lazy loading
#> Error: package or namespace load failed for 'tidyverse':
#>     .onAttach failed in attachNamespace() for 'tidyverse', details:
#>     call: NULL
#> error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
#> Error: package 'tidyverse' could not be loaded
#> Execution halted
#> ERROR: lazy loading failed for package 'adventr'
#> * removing 'C:/Users/hp/Documents/R/win-library/3.6/adventr'
#> Error: Failed to install 'adventr' from GitHub:
#>     (converted from warning) installation of package ‘C:/Users/hp/AppData/Local/Temp/Rtmpchl0S4/file1a802f4370d9/adventr_0.1.6.tar.gz’ had non-zero exit status
```

**Comment by profandyfield** [comment]
I believe adventr is built under 3.6.3, so it should fail anyway under 3.6.2 shouldn't it? I'm not sure it makes sense to move learnr to imports because you need it attached to run a tutorial. Tidyverse could be moved. Would this solve your problem though because imports will still try to install won't it ([http://r-pkgs.had.co.nz/namespace.html](http://r-pkgs.had.co.nz/namespace.html))? I'll admit ... I'm a newbie when it comes to writing packages, so feel free to educate me.

**Comment by hplieninger** [comment]
Installing tidyverse and learnr (i.e., having them in `Imports`) is no problem. The problem only arises if they are in `Depends`, because `install_github()` checks if adventr can be attached *without warnings*. However, attaching adventr currently also attaches, for example, ggplot2. And if ggplot2 was build (on CRAN) using a different R version, I will get a warning.

When I install your package from GitHub, I have to *build* it myself from source. Thus, it is built using my R version irrespective of the version you are using. This is different for binary packages (e.g., on CRAN), at least AFAIK.

I don't know how you recommend using the tutorials. But one way would be to (1) install learnr, (2) install adventr, and then (3) either click on the tutorial in the [new RStudio Tutorial pane](https://blog.rstudio.com/2020/02/25/rstudio-1-3-integrated-tutorials/) or run `learnr::run_tutorial("adventr_01", package = "adventr")`. For this, tidyverse and learnr can safely be in `Imports` IMHO.

If tidyverse is in `Imports`, you can use tidyverse functions like this: `dplyr::select()`. If, addtionally, you `@import tidyverse`, you can use tidyverse functions like this: `select()`. If you want your users to be able to use tidyverse functions, you can manually `@export` them (see `usethis::use_pipe()` for an example), or put the whole package in `Depends`. Since you probably want users---inside a tutorial---to manually attach a package via `library()`, I don't think you need to have tidyverse or learnr in `Imports`.

Last, note that if you plan on submitting to CRAN one day, you should rather not list tidyverse but the individual package in the DESCRIPTION (see https://www.tidyverse.org/blog/2018/06/tidyverse-not-for-packages/).

Puh, did not expect this to get that long. Hope there is at least something helpful in there.

**Comment by profandyfield** [comment]
Thanks. I have moved tidyverse out of Depends/Imports. As per your suggestion, for CRAN submission (now accepted, and thanks because this thread prompted me to get onto that ....) I now only have Imports for specific tidyverse packages (ggplot2, dplyr etc.).

I *think* (although I'm still unclear on this) that I have to have learnr in Depends because you can't run a tutorial without it.

**Comment by hplieninger** [comment]
Cool, congratulations to the CRAN acceptance!

_I think_ it's not needed to have learnr in Depends, but it also does not do any harm, so why bother.
