### ISSUE TITLE
adventr: data basics - complete exercises to continue

### ISSUE THREAD

**Issue by Leesahd** [profandyfield/adventr#13]
I am new to the tutorials and as I work through them I cannot continue with the "try it yourself" parts
I have tried entering the Hint passage and running it however when I go to continue the message "You must complete the exercises in this section before continuing." comes up, is there a reason I cannot continue?

**Comment by luiandresgonzalez** [comment]
Just to confirm that this is happening to me as well. In my case, refreshing the window solves the issue, but a colleague cannot advance in their system. Running R version 4.1.3 (2022-03-10) on Windows 10, with learnr 0.11.5 and adventr 0.1.8

**Comment by profandyfield** [comment]
I'd maybe switch to these tutorials as I'm a bit more on top of maintaining them: https://github.com/profandyfield/discovr
