### ISSUE TITLE
Failing to load in the browser

### ISSUE THREAD

**Issue by ghost** [profandyfield/adventr#2]
Hey, this package sounds amazing, but I'm hitting a wall right off the bat. Everything goes well, until a blank web page loads and this output comes up:

```
> library(adventr)
> learnr::run_tutorial("adventr_03", package = "adventr")
Loading required package: shiny
Warning: package ‘learnr’ was built under R version 3.4.2
Warning: package ‘tidyverse’ was built under R version 3.4.2
── Attaching packages ─────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ readr   1.1.1
✔ tibble  1.3.4     ✔ purrr   0.2.4
✔ tidyr   0.7.2     ✔ dplyr   0.7.4
✔ ggplot2 2.2.1     ✔ stringr 1.2.0
Warning: package ‘tidyr’ was built under R version 3.4.2
Warning: package ‘purrr’ was built under R version 3.4.2
Warning: package ‘dplyr’ was built under R version 3.4.2
── Conflicts ────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Listening on http://127.0.0.1:6051
Warning: Error in normalizePath: path[1]="": No such file or directory
Stack trace (innermost first):
    8: <Anonymous>
    7: do.call
    6: rmarkdown::run
    5: force
    4: withr::with_envvar
    3: force
    2: withr::with_dir
    1: learnr::run_tutorial
Error : path[1]="": No such file or directory
```

On MacOS and Chrome, R is version 3.4.1.

**Comment by amsantac** [comment]
The package seems promising. I got the same error as above:

```
Listening on http://127.0.0.1:3921
Warning: Error in normalizePath: path[1]="": No such file or directory
Stack trace (innermost first):
    8: <Anonymous>
    7: do.call
    6: rmarkdown::run
    5: force
    4: withr::with_envvar
    3: force
    2: withr::with_dir
    1: learnr::run_tutorial
Error : path[1]="": No such file or directory
```

My session info:

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.2.0      dplyr_0.7.4        purrr_0.2.4        readr_1.1.1        tidyr_0.7.2        tibble_1.4.1       ggplot2_2.2.1     
 [8] tidyverse_1.2.1    RefManageR_0.14.20 learnr_0.9.1       forcat
```

**Comment by ginolhac** [comment]
Same issue here, unfortunately. The package looks indeed very promising

```
Session info ------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin16.7.0        
 ui       RStudio (1.2.156)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Madrid               
 date     2018-01-17                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------------
 package     * version    date       source                                
 adventr       0.1.0      2018-01-17 Github (profandyfield/adventr@f85c985)
```

**Comment by profandyfield** [comment]
Leave it with me, I'll try to look into it today ....

**Comment by profandyfield** [comment]
OK, I'm wondering if this is a file permissions issue. The package 'effects' has this strange quirk of trying to write a PDF called RPlot when it loads - I'm wondering whether having it wrapped up in a package and auto-loading is throwing an error because of some file permission thing. I've updated the files to remove the import of effects. Can someone give it a go to see whether it works? If so, I'll have to tweak a few tutorials that rely on effects, but that's a relatively minor issue ....

**Comment by ghost** [comment]
*edit* Am dumb. The install now fails with this message:

```
> install_github("profandyfield/adventr")
Downloading GitHub repo profandyfield/adventr@master
from URL https://api.github.com/repos/profandyfield/adventr/zipball/master
Installation failed: cannot open file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/adventr/R/adventr.rdb': No such file or directory
Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/Vancouver'
```
Gonna see if I can find a way around.

*edit edit* A full restart R and Rstudio let the install work - same timezone error, but it's installed now. However, there don't seem to be any lessons installed:

```
Error in learnr::run_tutorial("r_data_basics", package = "adventr") : 
  Tutorial r_data_basics was not found in the adventr package.
```

*final edit*

Manually downloading and adding the tutorials to the installed package brings us back to the same error we started with. I'm gonna leave the above so others don't go through the same process -.-

```
> learnr::run_tutorial("adventr_01", package = "adventr")
Loading required package: shiny
Warning: package ‘learnr’ was built under R version 3.4.2
Warning: package ‘tidyverse’ was built under R version 3.4.2
── Attaching packages ────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ purrr   0.2.4
✔ tibble  1.3.4     ✔ dplyr   0.7.4
✔ tidyr   0.7.2     ✔ stringr 1.2.0
✔ readr   1.1.1     ✔ forcats 0.2.0
Warning: package ‘tidyr’ was built under R version 3.4.2
Warning: package ‘purrr’ was built under R version 3.4.2
Warning: package ‘dplyr’ was built under R version 3.4.2
── Conflicts ───────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Listening on http://127.0.0.1:4853
Warning: Error in normalizePath: path[1]="": No such file or directory
Stack trace (innermost first):
    8: <Anonymous>
    7: do.call
    6: rmarkdown::run
    5: force
    4: withr::with_envvar
    3: force
    2: withr::with_dir
    1: learnr::run_tutorial
Error : path[1]="": No such file or directory
```

Unsure if it's relevant, but trying to render the tutorial Rmd files in isolation fails as well:

```
pandoc-citeproc: Could not find ../../doc/adventr_bib.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Pandoc
pandoc: Error running filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83
Execution halted
```

**Comment by ghost** [comment]
Fresh comment for fresh info! Following the reference to the .bib file in the above error, a process that makes the run_tutorial function work:

Open the adventr_#.Rmd, comment out line 8, run the first chunk, knit the file. The tutorial can now be ran.

```
# bibliography: ../../doc/adventr_bib.bib <- comment out
```

```
learnr::run_tutorial("adventr_0#", package = "adventr") <- This command now works.
```

It works for all the tutorials, and seems to be generating the "ais_0#_files" folder, so maybe it's getting around the permissions issue somehow, or the bibliography file is broken somehow? Was there a mistake in the Nov. 27th commit where the "redundant bib files" were removed?

**Comment by fubits1** [comment]
> `# bibliography: ../../doc/adventr_bib.bib <- comment out`
confirmed!
 
![grafik](https://user-images.githubusercontent.com/13749354/35062839-acc820d8-fbc5-11e7-975d-f7f7eeb5bd77.png)

**Comment by profandyfield** [comment]
learnr::run_tutorial("r_data_basics", package = "adventr") is not correct, the tutorial is adventr_02 so you'd need to run:

learnr::run_tutorial("adventr_02", package = "adventr")

**Comment by profandyfield** [comment]
I've re-uploaded editing out all the relative paths to the bib files,a nd instead locating separet bib files in each tutorial directory .... 

thanks for the great feedback. Let me know if any of this is getting me closer to a package that works on other people's machines;)

**Comment by ghost** [comment]
Re: "r_data_basics" - I realized that eventually. It's still on the vingette at https://github.com/profandyfield/adventr/blob/master/vignettes/using_adventr.Rmd

Re: The changes: Seems to have done the trick! A full restart/reinstall and no bugs except that time-zone one that doesn't seem to matter.

**Comment by amsantac** [comment]
It works now! Thanks a lot

Awesome work!

**Comment by profandyfield** [comment]
@lucasjfriesen I forgot I had a vignette - thanks for pointing that out. I've updated it.
Now it's working I might re-introduce the effects package and see whether this breaks it again ... as it stands not sure whether it was only the bib files messing things up or effects as well.

**Comment by ghost** [comment]
Fresh session + install under the new build seems to work fine.

**Comment by profandyfield** [comment]
awesome - thanks for checking it. That is very handy to be able to leave effects in ...

Thanks again for the invaluable feedback. I've learnt a lot today about how when things seem to work fine in your development environment you shouldn't assume they'll work on other people's computers;) I really appreciate your time and effort today. cheers.
