### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by profandyfield** [profandyfield/adventr#4]
@RodrigoDalBen reposted from [learnr thread](https://github.com/rstudio/learnr/issues/169#issuecomment-407383199)
----------
Hello all,
@profandyfield
I had the same problem described above, so I re-installed "adventr". However, I encountered another problem when trying to run tutorial 11:

> library(adventr)
> learnr::run_tutorial("adventr_11", package = "adventr")
Error: lexical error: invalid char in json text.
                                       <<<<<<< HEAD {"type":"list","at
                     (right here) ------^
Tutorials 1, 2, 3 works fine, but from 04 on the same error occur. How can I fix this?

**Comment by profandyfield** [comment]
Seemed to be something to do with the function I was using to display tips in a different coloured font. (Although I'm not sure why tutorials 1-3 worked ...). I've re-rendered all of the tutorials, so try reinstalling and let me know how you get on.

**Comment by RodDalBen** [comment]
@profandyfield 
Sorry for the late feedback! 
All tutorials are working now! Thanks!! =)
