### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by braunsb** [profandyfield/adventr#7]
Just upgraded to R 3.6 (and it feels like a downgrade, what with all the problems with packages). When I tried to install `adventr` I got this message:

Error: HTTP error 401.
  Bad credentials

  Rate limit remaining: 56/60
  Rate limit reset at: 2019-05-16 19:04:18 UTC

**Comment by profandyfield** [comment]
yeah, everytime R upgrades I have to re-render the tutorials - it's a pain! Probably that's the issue. I'll do it next week.

**Comment by braunsb** [comment]
Alas! I'm teaching on Thursday next week. 

I've jumped ship from swirlify, which has somehow not been included in this release of R. Something about checks. I think my students are all going to have R 3.6 because they're downloading the software next week. Gosh… maybe I'll have to… lecture. The poor attendees.

**Comment by profandyfield** [comment]
I can have a look Monday - just not tomorrow. Worst case you could use the raw rmd files from github and get students to knit the file to activate the tutorial. Hopefully though if I re-render on Monday all will be fine. (If indeed that is the issue rather than some other funk introduced by 3.6)

**Comment by braunsb** [comment]
Thanks very much. That’s very kind of you.

**Comment by profandyfield** [comment]
I've spent the day editing all of the tutorials in various ways (i.e. stuff on my to-do list that I need to do before I start teaching with these again!) They are now all re-rendered under R 3.6.0. Try re-installing and see if it's fixed the issue. Hopefully it has ....

**Comment by braunsb** [comment]
I'm still getting bad credentials with this command sequence:

>library(remotes)
>install_github("profandyfield/adventr")

**Comment by braunsb** [comment]
Error: HTTP error 401.
  Bad credentials

  Rate limit remaining: 47/60
  Rate limit reset at: 2019-05-20 18:05:38 UTC

**Comment by profandyfield** [comment]
Oh, have you tried installing something else from github to check it’s not an issue with install_github() or checked the remotes github page? Might be worth installing the latest dev version of remotes too.

**Comment by braunsb** [comment]
No, I have not. But I will now.

**Comment by profandyfield** [comment]
I've just tried installing (R 3.6.0 on MacOS) and had no issues (see attached), which suggests to me it isn't adventr that's the problem.

![2019-05-20_22-21-14](https://user-images.githubusercontent.com/11991560/58052776-a4da9f00-7b4d-11e9-8af2-020384580c98.png)

**Comment by braunsb** [comment]
Thank you for looking into that. I agree, adventr is not the problem. I’m looking forward to solving this and starting to use the package!

Sheila

**Comment by profandyfield** [comment]
Looks like a similar issue [here](https://github.com/James-Thorson-NOAA/VAST/issues/147). I also found another package for installing from github - see [here](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html). Maybe try that and see if you have the same problem.

**Comment by braunsb** [comment]
Yes, that is the exact same problem. I just tried installing devtools again but the "bad credentials" error persists.

**Comment by braunsb** [comment]
I just tried this (based on the first link in your last comment):

utils::install.packages( pkgs="adventr", repos='http://cran.us.r-project.org' )
Warning message:
package ‘adventr’ is not available (for R version 3.6.0)

**Comment by profandyfield** [comment]
utils::install.packages( pkgs="adventr", repos='http://cran.us.r-project.org' )

won't work because the package isn't posted on CRAN - only GitHub - so you need to install direct from GitHub. Try the other link, which might work if the problem is to do with devtools.

**Comment by braunsb** [comment]
Oh of course. How embarrassing.

**Comment by braunsb** [comment]
It’s not you; it’s us. We have very tough security stuff going on. Thanks for all your help.
