### ISSUE TITLE
Progress! But missing an html file

### ISSUE THREAD

**Issue by braunsb** [profandyfield/adventr#8]
Hi there,

I finally managed to get everything working on R 3.6, got past the Personal Access Token change requirement, and downloaded your package. When I tried to start a lesson, this is what happened:

>learnr::run_tutorial("adventr_02", package = "adventr")    
Error in shiny_prerendered_html(input_rmd, encoding, render_args) :     
  Prerendered HTML file not found at ./ais_02_old.html    

This seems to be related to a prior issue, but I wasn't able to follow the thread. Is there something I can do to fix this? Thanks!

**Comment by profandyfield** [comment]
Looks like there was an old RMD tutorial lurking in the adventr_02 folder with no associated html. That might have been confusing things ... (i.e. it wasn't lookingf or the correct html file).  I've deleted that RMD and pushed to github, try re-installing and see if it works.

**Comment by braunsb** [comment]
Works beautifully. Thanks!
