### ISSUE TITLE
Completion of previous tutorials required?

### ISSUE THREAD

**Issue by SCiccarelli** [profandyfield/adventr#9]
I wasn't sure where else to ask this, but I'm attempting to jump around and look at the tutorials without completing them to get an idea of what they actually practice and cover. However, I'm not allowed to click anything in the web browser. Is this because I haven't completed previous tutorials?

**Comment by profandyfield** [comment]
Probably. The tutorials are set so that the user is forced to complete code tasks before moving on.

**Comment by profandyfield** [comment]
Ps If you clone the github repo you can see what is covered by looking at the raw RMD files.
